import { useMemo, useState } from 'react';
import { Bell, CalendarDays, Check, ChevronRight, CircleUserRound, Clock3, FolderKanban, Home, Inbox, ListTodo, LogOut, Menu, Mic, MoreHorizontal, Plus, Search, Settings, SlidersHorizontal, Sparkles, Sun, Users, WandSparkles, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Drawer, DrawerContent, DrawerDescription, DrawerHeader, DrawerTitle } from '@/components/ui/drawer';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Progress } from '@/components/ui/progress';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { toast } from 'sonner';
import { NotionSettings } from '@/components/NotionSettings';
import { useDone } from '@/contexts/DoneContext';
import { useSession } from '@/contexts/SessionContext';
import { doneVoice, parseCapture, priorityEngine, Task } from '@/lib/done';

type View='now'|'tasks'|'projects'|'household'|'settings';
const nav=[{id:'now',label:'Now',icon:Sun},{id:'tasks',label:'Everything',icon:ListTodo},{id:'projects',label:'Projects',icon:FolderKanban},{id:'household',label:'Us',icon:Users},{id:'settings',label:'Settings',icon:Settings}] as const;
function Wordmark(){return <div className="brand text-[27px]">DONE<span>.</span></div>}
function TaskRow({task,onDone,onSnooze,big=false}:{task:Task;onDone:()=>void;onSnooze?:()=>void;big?:boolean}){const{data}=useDone();const category=data.categories.find(c=>c.id===task.category);const member=data.members.find(m=>m.id===task.assignee);return <article className={`group flex items-start gap-3 ${big?'paper-card p-4 sm:p-5':'border-b py-4 last:border-0'}`}>
  <button aria-label={`Complete ${task.title}`} onClick={onDone} className={`mt-0.5 flex shrink-0 items-center justify-center rounded-full border-2 border-foreground/25 transition hover:border-primary hover:bg-secondary ${big?'h-8 w-8':'h-7 w-7'}`}>{task.completed&&<Check size={16}/>}</button>
  <div className="min-w-0 flex-1"><h3 className={`${big?'text-[17px]':'text-[15px]'} font-bold leading-snug ${task.completed?'line-through opacity-45':''}`}>{task.title}</h3><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">{task.due&&<span className={`rounded-full px-2.5 py-1 font-bold ${task.due==='Today'?'bg-[#f8ddd4] text-[#a64937]':'bg-muted'}`}>{task.due}</span>}<span className="rounded-full px-2.5 py-1" style={{backgroundColor:category?.color}}>{category?.name}</span><span className="flex items-center gap-1"><span className="h-4 w-4 rounded-full text-center text-[9px] font-bold leading-4 text-white" style={{background:member?.color}}>{member?.initial}</span>{member?.name}</span></div></div>
  {onSnooze&&<button onClick={onSnooze} className="rounded-full p-2 text-muted-foreground hover:bg-muted" aria-label="Not now"><Clock3 size={17}/></button>}
</article>}
function Empty(){return <div className="py-14 text-center"><div className="relative mx-auto mb-5 h-32 w-48"><div className="absolute bottom-2 left-5 h-8 w-36 rounded-[50%] bg-[#ddefd8]"/><div className="absolute left-12 top-4 h-20 w-24 rotate-[-5deg] rounded-2xl border-2 border-foreground bg-card p-3"><Check className="mx-auto mt-3 text-primary" size={32}/></div><div className="absolute bottom-5 right-4 rotate-12 text-4xl">🕶️</div></div><h2 className="text-2xl">The coast is clear.</h2><p className="mx-auto mt-2 max-w-xs text-muted-foreground">{doneVoice.empty}</p></div>}
function NowView({complete,snooze}:{complete:(id:string)=>void;snooze:(id:string)=>void}){const{data}=useDone();const big3=priorityEngine(data.tasks);const remaining=data.tasks.filter(t=>!t.completed&&!big3.some(b=>b.id===t.id));return <div className="animate-in-soft"><div className="mb-7"><p className="eyebrow">Tuesday · 18 August</p><h1 className="mt-2 text-4xl leading-none sm:text-5xl">Good morning.<br/><em>Here’s enough.</em></h1></div>
  <section><div className="mb-3 flex items-end justify-between"><div><p className="eyebrow text-primary">Your Big 3</p><p className="mt-1 text-sm text-muted-foreground">Picked for impact, urgency & energy.</p></div><WandSparkles className="text-primary" size={21}/></div><div className="space-y-3">{big3.map((task,i)=><div key={task.id} style={{animationDelay:`${i*70}ms`}} className="animate-in-soft"><TaskRow task={task} big onDone={()=>complete(task.id)} onSnooze={()=>snooze(task.id)}/></div>)}</div></section>
  {big3.length===0?<Empty/>:<section className="mt-8"><div className="mb-1 flex items-center justify-between"><p className="eyebrow">Waiting in the wings</p><span className="text-xs font-bold text-muted-foreground">{remaining.length} more</span></div>{remaining.slice(0,3).map(t=><TaskRow key={t.id} task={t} onDone={()=>complete(t.id)}/>)}</section>}</div>}
function TasksView({complete}:{complete:(id:string)=>void}){const{data}=useDone();const[query,setQuery]=useState('');const[triage,setTriage]=useState(false);const active=data.tasks.filter(t=>!t.completed&&t.title.toLowerCase().includes(query.toLowerCase()));const triageItems=active.filter(t=>!t.due).slice(0,3);return <div className="animate-in-soft"><div className="flex items-end justify-between"><div><p className="eyebrow">The whole lot</p><h1 className="mt-1 text-4xl">Everything</h1></div><Button onClick={()=>setTriage(!triage)} variant="outline" className="rounded-full"><SlidersHorizontal size={16} className="mr-2"/>Triage</Button></div>
  {triage&&<div className="my-5 rounded-[1.75rem] bg-foreground p-5 text-background"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#9dddab]">Anti-overwhelm mode</p><h2 className="mt-1 text-2xl">Three loose ends. That’s all.</h2></div><button onClick={()=>setTriage(false)}><X/></button></div><div className="mt-4 space-y-2">{triageItems.map(t=><div key={t.id} className="flex items-center gap-3 rounded-2xl bg-white/10 p-3"><button onClick={()=>complete(t.id)} className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-white/50"><Check size={14}/></button><span className="flex-1 text-sm font-bold">{t.title}</span><button className="text-xs text-white/70">Later</button></div>)}</div></div>}
  <div className="relative my-5"><Search className="absolute left-4 top-3.5 text-muted-foreground" size={19}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find anything..." className="h-12 rounded-full bg-card pl-12"/></div><div className="paper-card px-5">{active.length?active.map(t=><TaskRow key={t.id} task={t} onDone={()=>complete(t.id)}/>):<Empty/>}</div>
  <div className="mt-7"><p className="eyebrow mb-3">By category</p><div className="grid grid-cols-2 gap-3">{data.categories.map(c=><button key={c.id} className="rounded-3xl p-4 text-left transition hover:-translate-y-0.5" style={{background:c.color}}><span className="font-bold">{c.name}</span><p className="mt-1 text-xs opacity-60">{c.owner?`${c.owner} · `:''}{data.tasks.filter(t=>t.category===c.id&&!t.completed).length} open</p></button>)}</div></div></div>}
function ProjectsView(){const{data}=useDone();return <div className="animate-in-soft"><p className="eyebrow">Keep the big stuff moving</p><h1 className="mt-1 text-4xl">Projects</h1><div className="mt-6 grid gap-4 sm:grid-cols-2">{data.projects.map(p=><article key={p.id} className="paper-card overflow-hidden"><div className="p-5" style={{background:p.color}}><div className="flex justify-between text-3xl"><span>{p.emoji}</span><MoreHorizontal/></div><h2 className="mt-8 text-2xl leading-tight">{p.name}</h2></div><div className="p-5"><div className="mb-2 flex justify-between text-xs font-bold"><span>{p.completed} of {p.total} done</span><span>{Math.round(p.completed/p.total*100)}%</span></div><Progress value={p.completed/p.total*100} className="h-2"/><button className="mt-4 flex items-center gap-1 text-sm font-bold text-primary">Open project <ChevronRight size={16}/></button></div></article>)}<button className="flex min-h-44 items-center justify-center rounded-[1.75rem] border-2 border-dashed text-muted-foreground hover:border-primary hover:text-primary"><Plus className="mr-2"/>Start a project</button></div></div>}
function HouseholdView(){const{data}=useDone();return <div className="animate-in-soft"><p className="eyebrow">The home team</p><h1 className="mt-1 text-4xl">Your people</h1><p className="mt-2 text-muted-foreground">Share the load without keeping score.</p><div className="mt-6 space-y-3">{data.members.map((m,i)=><article key={m.id} className="paper-card flex items-center gap-4 p-4"><Avatar className="h-14 w-14 border-4 border-card"><AvatarFallback style={{background:m.color}} className="text-lg font-bold text-white">{m.initial}</AvatarFallback></Avatar><div className="flex-1"><h3 className="text-lg font-bold">{m.name}</h3><p className="text-sm text-muted-foreground">{data.tasks.filter(t=>t.assignee===m.id&&!t.completed).length} things on their plate</p></div><ChevronRight className="text-muted-foreground"/></article>)}<button className="flex w-full items-center gap-4 rounded-[1.75rem] border-2 border-dashed p-4 text-left text-muted-foreground"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-muted"><Plus/></span><span className="font-bold">Invite someone</span></button></div><div className="mt-8 rounded-[2rem] bg-[#e9f4e6] p-6"><p className="eyebrow text-primary">House rule</p><h2 className="mt-2 text-2xl">Nobody has to remember everything.</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">DONE. holds the details so your people can get on with being people.</p></div></div>}
function SettingsView(){const{data,toggleSetting}=useDone();const{session,demo,signOut}=useSession();const items=[['doneVoice','DONE. voice','Warm, occasional nudges'],['celebrations','Little celebrations','A small moment when it matters'],['quietHours','Quiet hours','No nudges after 8pm']] as const;return <div className="animate-in-soft"><p className="eyebrow">Make it yours</p><h1 className="mt-1 text-4xl">Settings</h1><div className="paper-card mt-6 px-5">{items.map(([key,label,desc])=><div key={key} className="flex items-center gap-4 border-b py-5 last:border-0"><div className="flex-1"><p className="font-bold">{label}</p><p className="text-sm text-muted-foreground">{desc}</p></div><Switch checked={data.settings[key]} onCheckedChange={()=>toggleSetting(key)}/></div>)}</div><NotionSettings/><div className="paper-card mt-4 p-5"><p className="font-bold">Coming next</p><p className="mt-1 text-sm text-muted-foreground">Voice capture, AI sorting and family notifications are ready for a future phase.</p><div className="mt-4 flex flex-wrap gap-2">{['Voice','AI helper','Notifications'].map(x=><span key={x} className="rounded-full bg-muted px-3 py-1.5 text-xs font-bold">{x} · Soon</span>)}</div></div><button onClick={signOut} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full border py-3 text-sm font-bold"><LogOut size={17}/>{demo?'Leave demo':`Sign out ${session?.user.email??''}`}</button></div>}
function Capture({open,onOpenChange}:{open:boolean;onOpenChange:(o:boolean)=>void}){const{addTask}=useDone();const[text,setText]=useState('');const submit=()=>{if(!text.trim())return;const parsed=parseCapture(text);addTask({...parsed,id:crypto.randomUUID(),completed:false,createdAt:new Date().toISOString()});setText('');onOpenChange(false);toast.success(doneVoice.capture)};return <Drawer open={open} onOpenChange={onOpenChange}><DrawerContent className="mx-auto max-w-xl rounded-t-[2rem] bg-card"><DrawerHeader className="text-left"><DrawerTitle className="text-3xl">Drop it here.</DrawerTitle><DrawerDescription>Write it like you’d say it. We’ll sort the details.</DrawerDescription></DrawerHeader><div className="px-4 pb-8"><div className="rounded-[1.5rem] border-2 border-primary/30 bg-background p-3"><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}} className="min-h-28 w-full resize-none bg-transparent p-2 text-lg outline-none" placeholder="e.g. Pick up Milo’s shoes tomorrow for Sam"/><div className="flex items-center justify-between"><button className="rounded-full p-3 text-primary"><Mic/></button><Button onClick={submit} className="rounded-full px-6 font-bold">Add it <ArrowIcon/></Button></div></div><p className="mt-3 text-center text-xs text-muted-foreground">Try a person, day or place — DONE. will catch it.</p></div></DrawerContent></Drawer>}
function ArrowIcon(){return <ChevronRight className="ml-1" size={17}/>}
export default function Index(){const[view,setView]=useState<View>('now');const[capture,setCapture]=useState(false);const[celebrate,setCelebrate]=useState(false);const{data,toggleTask,snoozeTask}=useDone();const complete=(id:string)=>{const task=data.tasks.find(t=>t.id===id);toggleTask(id);if(task&&!task.completed){toast.success(data.settings.doneVoice?doneVoice.complete[Math.floor(Math.random()*doneVoice.complete.length)]:'Done.');if(data.settings.celebrations&&data.tasks.filter(t=>t.completed).length%3===2)setCelebrate(true)}};const content=useMemo(()=>view==='now'?<NowView complete={complete} snooze={snoozeTask}/>:view==='tasks'?<TasksView complete={complete}/>:view==='projects'?<ProjectsView/>:view==='household'?<HouseholdView/>:<SettingsView/>,[view,data]);return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r bg-card/95 p-7 lg:flex lg:flex-col"><Wordmark/><p className="mt-2 text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">Do · Organize · Now · Enjoy</p><nav className="mt-12 space-y-2">{nav.map(n=><button key={n.id} onClick={()=>setView(n.id)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold transition ${view===n.id?'bg-secondary text-primary':'text-muted-foreground hover:bg-muted'}`}><n.icon size={19}/>{n.label}</button>)}</nav><div className="mt-auto rounded-3xl bg-[#f8ddd4] p-4"><Sparkles size={20} className="text-[#bd5b47]"/><p className="mt-3 text-sm font-bold">Your family has finished {data.tasks.filter(t=>t.completed).length+12} things this week.</p><p className="mt-1 text-xs text-muted-foreground">No streaks. No guilt. Just progress.</p></div></aside>
  <header className="sticky top-0 z-20 border-b bg-background/90 px-5 py-4 backdrop-blur lg:ml-64"><div className="mx-auto flex max-w-3xl items-center justify-between"><div className="lg:hidden"><Wordmark/></div><div className="hidden lg:block"><p className="text-sm font-bold text-muted-foreground">Our household</p></div><div className="flex items-center gap-2"><button className="rounded-full p-2.5 hover:bg-muted"><Bell size={20}/></button><button onClick={()=>setView('household')} className="flex h-9 w-9 items-center justify-center rounded-full bg-foreground text-xs font-bold text-background">Y</button></div></div></header>
  <main className="px-5 pb-32 pt-7 lg:ml-64 lg:pb-16"><div className="mx-auto max-w-3xl">{content}</div></main>
  <Button onClick={()=>setCapture(true)} className="fixed bottom-[5.4rem] right-5 z-30 h-14 rounded-full px-5 text-base font-bold shadow-[0_12px_30px_rgba(57,168,82,.3)] lg:bottom-8 lg:right-8"><Plus className="mr-2"/>Quick add</Button>
  <nav className="safe-bottom fixed inset-x-0 bottom-0 z-20 border-t bg-card/95 px-2 pt-2 backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg items-center justify-around">{nav.slice(0,4).map(n=><button key={n.id} onClick={()=>setView(n.id)} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl py-1.5 text-[10px] font-bold ${view===n.id?'text-primary':'text-muted-foreground'}`}><n.icon size={20} strokeWidth={view===n.id?2.7:2}/>{n.label}</button>)}<button onClick={()=>setView('settings')} className={`flex min-w-16 flex-col items-center gap-1 py-1.5 text-[10px] font-bold ${view==='settings'?'text-primary':'text-muted-foreground'}`}><Menu size={20}/>More</button></div></nav>
  <Capture open={capture} onOpenChange={setCapture}/><Dialog open={celebrate} onOpenChange={setCelebrate}><DialogContent className="max-w-sm rounded-[2rem] bg-card text-center"><DialogHeader><div className="mx-auto flex h-28 w-28 rotate-[-5deg] items-center justify-center rounded-full bg-secondary"><Check className="pop text-primary" size={66} strokeWidth={3}/><span className="absolute translate-x-14 -translate-y-10 text-2xl">✦</span><span className="absolute -translate-x-14 translate-y-9 text-2xl">🍦</span></div><DialogTitle className="pt-3 text-center text-3xl">That was a big one.</DialogTitle><DialogDescription className="text-center text-base">Take the win. Maybe even the good biscuits.</DialogDescription></DialogHeader><Button onClick={()=>setCelebrate(false)} className="mt-2 rounded-full">Lovely, thanks</Button></DialogContent></Dialog></div>}
