// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = "https://lqbnfhiaygqhhcsyoosf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_QKxjqU7mnvOKSZS0iJFu2Q_Qbgvh0uq";
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
